spring.application.name=conta-bancaria
# Configuração do banco H2 em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Configuração JWT (exemplo)
# ===============================
# ${JWT_SECRET}
security.jwt.secret=mysupersecretkeymysupersecretkey123!
# 60*15 // 15 minutos
security.jwt.access-expiration= 900
# 60*60*24*7 // 7 dias
security.jwt.refresh-expiration= 604800

server.address=0.0.0.0
server.port=8080

# ===============================
# Configuração do Admin Provisório
# ===============================
sistema.admin.email=admin@senai.com
sistema.admin.senha=admin123
